version: "3"

services:
  apache:
    build: 
      context: .
      dockerfile: "./Dockerfile"
    # Php site
    volumes:
      - .:/var/www/html
    
    
    # SQL
      - ./database/todoDB.sqlite3:/var/www/html/database/todoDB.sqlite3
  
    ports:
      - "8080:80"
    
    environment:
      - SQLITE_DATABASE_PATH=/var/www/db/todoDB.sqlite3

    networks:
      - backend

    restart: always

networks:
  backend:
    driver: bridge