version: "3"

services:
  apache:
    build: 
      context: .
      dockerfile: "./Dockerfile"
    # Php site
    volumes:
      - ./database:/var/www/html/database
    
    
    # SQL
     # - ./database/:/var/www/html/database/
  
    ports:
      - "8080:80"
    
    #environment:
     # - SQLITE_DATABASE_PATH

    networks:
      - backend

    restart: always

networks:
  backend:
    driver: bridge